name: rdfx
channels:
  - conda-forge
dependencies:
  - pyscal3 =3.1.0
  - rdflib
  - pyyaml
  - jupyterlab
  - graphviz
  - python-graphviz
  - pyyaml
  - ase 
  - ipycytoscape
  - voila
  - plotly
  - jupyterlab-dash
  - networkx
  - pyscal-rdf =0.0.7
