name: rdf
channels:
  - conda-forge
dependencies:
  - python >3.8
  - pyscal3 = 3.1.0
  - pyscal_rdf
  - rdflib
  - pyyaml
  - jupyterlab
  - graphviz
  - python-graphviz
  - pyyaml
  - ase 
  - ipycytoscape
  - voila
  - plotly
  - jupyterlab-dash
  - networkx
