name: testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]
        python-version: [3.9, '3.10']

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: rdfx
        environment-file: environment.yml
        python-version: ${{ matrix.python-version }}
    
    - name: run tests
      shell: bash -l {0}
      run: |
        pip install -e .
        pip install pytest
        pip install pytest-cov
        pytest tests/
        #pytest --cov-report=xml --cov=pyscal tests/    
